on:
  push:
    paths:
      - 'namedivider-python/**'
name: update-assets
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      - name: update-csv
        run: cd namedivider-python && make download-csv
      - name: Commit assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add namedivider-python/assets
          git commit -m "chore: update assets" -a
          git push
